### ISSUE TITLE
Refreshing the RubberNugget webapp triggers a hard crash

### ISSUE THREAD

**Issue by skickar** [HakCat-Tech/RubberNugget#7] opened 2022-04-26 07:56 UTC
When adding new payloads, the web interface will sometimes crash hard, and will not come back up until a reboot.

Issue seems possibly related to pasting? Deleting the new folders will sometimes fix the issue, other times it won't.

Issue may be related to multiple payloads with the same name. Comes up when creating payloads in other OS category folders.

Only way to fix is hit reset button or unplug and plug in again.

Symptoms: 

1. USB device disconnects (reboot) and neopixel turns off (if it was on)
2. Web request hangs (no response)
3. Rolling back last file operation does not fix the issue
4. Unplug or reset button fixes issue

Noted that another user could connect but the current user could not make a successful web request.

**Comment by skickar** [comment] 2022-05-07 08:09
To reproduce this bug:

1. Connect to Nugget's AP
2. In browser, navigate to web interface at 192.168.4.1
3. Click the "Run" tab
4. Observe crash via USB disconnect, Wi-Fi disconnect

**Comment by AlexLynd** [comment] 2022-05-11 07:18
This issue is fixed in the latest release!  v1.0.3 mitigates this issue which was caused by a loop that creates a new String array every time a page is refreshed.

**Closed** 2022-05-11 07:19 UTC
